# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: shellexec@0
  inputs:
    code: |
      git checkout qa
      git pull https://$(gitusername):$(gitpassword)@github.com/rameshbalidi/azurecicd dev
      git merge dev
      
      git push https://$(gitusername):$(gitpassword)@github.com/rameshbalidi/azurecicd qa

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-stage'
    runOptions: 'commands'
    commands: |
      mysqldump -h $(dbhost) -u $(dbusername) -p$(dbpassword) $(dbname) |gzip > /home/ec2-user/dbbackup$(date +%Y_%m_%d__%H_%M_%S$%M%S).sql.gz
      
      mysql -u $(dbusername)
      drop database $(dbname);
      
      create database rameshdb;
      
      grant all on rameshdb.* to 'ramesh'@'localhost';
      
      mysql -u $(dbusername) -p$(dbpassword) $(dbname) < /var/www/html/db/database.sql;
    readyTimeout: '20000'

# changing permissions to execute SSH task
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-stage'
    runOptions: 'commands'
    commands: 'sudo chmod -R 777 /var/www/html/'
    readyTimeout: '20000'


#Copying files to target path securely
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-stage'
    sourceFolder: '/home/vsts/work/1/s/'
    contents: '**'
    targetFolder: '/var/www/html/'
    readyTimeout: '20000'


#updating database
#- task: SSH@0
#  inputs:
#    sshEndpoint: 'ssh-stage'
#    runOptions: 'commands'
#    commands: 'sudo bash /home/ec2-user/database.sh'
#    readyTimeout: '20000'


#revoking file permissions as usual
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-stage'
    runOptions: 'commands'
    commands: 'sudo chmod -R 755 /var/www/html/'
    readyTimeout: '20000'