# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- qa

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

#Git merge task
- task: shellexec@0
  inputs:
    code: |
      git checkout master
      
      git pull https://$(gitusername):$(gitpassword)@github.com/rameshbalidi/azurecicd qa
      
      git merge qa
      
      git push https://$(gitusername):$(gitpassword)@github.com/rameshbalidi/azurecicd master

#Changing permissions to allow ssh tasks
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-prod'
    runOptions: 'commands'
    commands: 'sudo chmod -R 777 /var/www/html/'
    readyTimeout: '20000'

#copying files to target machine using SSH 
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-prod'
    sourceFolder: '/home/vsts/work/1/s/'
    contents: '**'
    targetFolder: '/var/www/html/'
    readyTimeout: '20000'

#updating database
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-prod'
    runOptions: 'commands'
    commands: 'sudo bash /home/ec2-user/database.sh'
    readyTimeout: '20000'

#revoking file permissions after completion of all tasks
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-prod'
    runOptions: 'commands'
    commands: 'sudo chmod -R 755 /var/www/html/'
    readyTimeout: '20000'